name: Terraform Apply Production
on:
  push:
    tags:
      - "*"
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID_PROD }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME_PROD }}
      PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER_PROD }}
      BILLING_ACCOUNT: ${{ secrets.BILLING_ACCOUNT_PROD }}
      POOL_ID: ${{ secrets.POOL_ID_PROD }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_PROD }}
      ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME_PROD }}
      IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID_PROD }}
      ENVIRONMENT: prod
    steps:
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.POOL_ID }}/providers/github-actions-provider'
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check Terraform Format
        run: terraform fmt -check -diff

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        run: terraform plan -lock-timeout=120s -var=project_id=${{ env.PROJECT_ID }} -var=project_name=${{ env.PROJECT_NAME }} -var=billing_account=${{ env.BILLING_ACCOUNT }} -var=android_package_name=${{ env.ANDROID_PACKAGE_NAME }} -var=ios_bundle_id=${{ env.IOS_BUNDLE_ID }} -var=env=${{ env.ENVIRONMENT }}

      - name: Run Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=120s -var=project_id=${{ env.PROJECT_ID }} -var=project_name=${{ env.PROJECT_NAME }} -var=billing_account=${{ env.BILLING_ACCOUNT }} -var=android_package_name=${{ env.ANDROID_PACKAGE_NAME }} -var=ios_bundle_id=${{ env.IOS_BUNDLE_ID }} -var=env=${{ env.ENVIRONMENT }}