name: Terraform Plan
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Check Terraform Format
        uses: hashicorp/terraform-github-actions@v1
        with:
          command: fmt
          args: ["-check", "-diff"]
      - name: Initialize Terraform
        uses: hashicorp/terraform-github-actions@v1
        with:
          command: init
      - name: Run Terraform Plan
        uses: hashicorp/terraform-github-actions@v1
        with:
          command: plan
          args: ["-lock-timeout=120s", "-var=project_id=${_PROJECT_ID}", "-var=project_name=${_PROJECT_NAME}", "-var=billing_account=${_BILLING_ACCOUNT}", "-var=android_package_name=${_ANDROID_PACKAGE_NAME}", "-var=ios_bundle_id=${_IOS_BUNDLE_ID}"]
timeout: "3600s"